#!/usr/bin/env bash

set -e

alert() {
  local red='\x1b[31;01m'
  local no_color='\x1b[39;49;00m'
  echo -e "🍗 ${red} $1${no_color}"
}

ask() {
  local yellow='\x1b[33;01m'
  local no_color='\x1b[39;49;00m'
  echo -e "🍗 ${yellow} $1${no_color}"
}

info() {
  local green='\x1b[32;01m'
  local no_color='\x1b[39;49;00m'
  echo -e "${green} $1${no_color}"
}

silent=0

while getopts 'hs' opt; do
  case $opt in
    h)
      echo "Usage: proof [-h] [-s]"
      exit 0
      ;;
    s)
      silent=1
      ;;
  esac
done

# Read configuration
config_file=.proofrc
if [ -e $config_file ]; then
  . $config_file
else
  alert "Could not find a config file for this project. Let's build one!"

  server=static.whazzmaster.com
  ask 'What server will this be pushed to? (default: '$server')'
  read g_server
  if [ -n "$g_server" ]; then
    server=$g_server
  fi

  target='dist'
  ask 'What local directory should be pushed? (default: ./'$target')'
  read g_target
  if [ -n "$g_target" ]; then
    target=$g_target
  fi

  name=${PWD##*/}
  ask 'What should the subdir name be on the server? (default: '$name')'
  read g_name
  if [ -n "$g_name" ]; then
    name=$g_name
  fi
fi

# Report configuration
echo
info 'The contents of ./'$target' will be available at http://'$server'/'$name
if [ $silent -eq 0 ]; then
  ask 'Shall we proceed? (Y/n)'
  read -n 1 proceed
  echo

  if [[ $proceed == 'n' || $proceed == 'N' ]]; then
    alert 'Aborting...'
    exit 1
  fi
fi
